[package]
name = "ide"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
dioxus = { version = "0.7.2", features = ["desktop"] }
dioxus-desktop = "0.7.2"
once_cell = "1.21.3"
regex = "1.12.2"
rfd = "0.17.1"
serde = "1.0.228"
toml = "0.9.10"

